name: CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  AI_MODEL_NAME: ${{ vars.AI_MODEL_NAME || 'gpt-4o' }}
  AI_MODEL_VERSION: ${{ vars.AI_MODEL_VERSION || '2024-11-20' }}
  AI_MODEL_DEPLOYMENT_NAME: ${{ vars.AI_MODEL_DEPLOYMENT_NAME || 'gpt-4o' }}

jobs:

  buildAndPush:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      imageTag: ${{ steps.imageTag.outputs.tag }}

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create image tag
      id: imageTag
      run: |
        branch=${{ github.ref_name }}
        echo "tag=${branch//'/'/'-'}-${{ github.run_number }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: metaWeb
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/horscht-web
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ steps.imageTag.outputs.tag }}

      # https://github.com/docker/build-push-action#inputs
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./Horscht.Web/Dockerfile
        push: true
        tags: ${{ steps.metaWeb.outputs.tags }}
        labels: ${{ steps.metaWeb.outputs.labels }}

    - name: Extract metadata (tags, labels) for Docker
      id: metaImporter
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/horscht-import
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ steps.imageTag.outputs.tag }}

      # https://github.com/docker/build-push-action#inputs
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./Horscht.Importer/Dockerfile
        push: true
        tags: ${{ steps.metaImporter.outputs.tags }}
        labels: ${{ steps.metaImporter.outputs.labels }}

  deploy:

    needs: buildAndPush

    runs-on: ubuntu-latest

    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Azure Resources
      id: deploy
      working-directory: deployment
      run: |
        output=$(az deployment sub create \
          --location ${{ vars.DEV_LOCATION }} \
          --name Horscht \
          --template-file main.bicep \
          --parameters \
            environment=dev \
            location=${{ vars.DEV_LOCATION }} \
            aspNetEnvironment=Development \
            adminUserIds=${{ secrets.DEV_ADMIN_USER_IDS }} \
            containerEnvironmentId=${{ vars.DEV_CONTAINER_ENVIRONMENT_ID }} \
            containerEnvironmentResourceGroupName=${{ vars.DEV_CONTAINER_ENVIRONMENT_RG }} \
            containerEnvironmentName=${{ vars.DEV_CONTAINER_ENVIRONMENT_NAME }} \
            registryUsername=${{ vars.DEV_REGISTRY_USERNAME }} \
            registryPassword=${{ secrets.DEV_REGISTRY_PASSWORD }} \
            imageTag=${{ needs.buildAndPush.outputs.imageTag }} \
            importerHostname=${{ vars.DEV_IMPORTER_HOSTNAME }} \
            apiHostname=${{ vars.DEV_API_HOSTNAME }} \
            authClientId=${{ vars.DEV_AUTH_CLIENT_ID }} \
            authClientSecret=${{ secrets.DEV_AUTH_CLIENT_SECRET }} \
            aiLocation=${{ vars.AI_LOCATION }} \
            aiModelName=${{ env.AI_MODEL_NAME }} \
            aiModelVersion=${{ env.AI_MODEL_VERSION }} \
            aiModelDeploymentName=${{ env.AI_MODEL_DEPLOYMENT_NAME }} \
          --output json)
        echo "resourceGroupName=$(echo "$output" | jq -r '.properties.outputs.resourceGroupName.value')" >> $GITHUB_OUTPUT
        echo "importerAppName=$(echo "$output" | jq -r '.properties.outputs.importerAppName.value')" >> $GITHUB_OUTPUT
        echo "importerCertificateId=$(echo "$output" | jq -r '.properties.outputs.importerCertificateId.value')" >> $GITHUB_OUTPUT
        echo "apiAppName=$(echo "$output" | jq -r '.properties.outputs.apiAppName.value')" >> $GITHUB_OUTPUT
        echo "apiCertificateId=$(echo "$output" | jq -r '.properties.outputs.apiCertificateId.value')" >> $GITHUB_OUTPUT

    - name: Bind Importer Hostname
      run: |
        az containerapp hostname bind \
          -g ${{ steps.deploy.outputs.resourceGroupName }} \
          -n ${{ steps.deploy.outputs.importerAppName }} \
          --hostname ${{ vars.DEV_IMPORTER_HOSTNAME }} \
          -c ${{ steps.deploy.outputs.importerCertificateId }}

    - name: Bind API Hostname
      run: |
        az containerapp hostname bind \
          -g ${{ steps.deploy.outputs.resourceGroupName }} \
          -n ${{ steps.deploy.outputs.apiAppName }} \
          --hostname ${{ vars.DEV_API_HOSTNAME }} \
          -c ${{ steps.deploy.outputs.apiCertificateId }}