name: CD

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: metaWeb
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/horscht-web

      # https://github.com/docker/build-push-action#inputs
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./Horscht.Web/Dockerfile
        push: true
        tags: ${{ steps.metaWeb.outputs.tags }}
        labels: ${{ steps.metaWeb.outputs.labels }}

    - name: Extract metadata (tags, labels) for Docker
      id: metaImporter
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/horscht-import

      # https://github.com/docker/build-push-action#inputs
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./Horscht.Importer/Dockerfile
        push: true
        tags: ${{ steps.metaImporter.outputs.tags }}
        labels: ${{ steps.metaImporter.outputs.labels }}