name: CI

on: [ push, pull_request, workflow_dispatch ]

env:
  IMAGE_TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Importer image
      run: docker build . --file ./Horscht.Importer/Dockerfile --tag horscht-importer:${{ env.IMAGE_TAG }}

    - name: Build the Web image
      run: docker build . --file ./Horscht.Web/Dockerfile --tag horscht-web:${{ env.IMAGE_TAG }}

    - name: Extract metadata (tags, labels) for Docker
      id: metaWeb
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/horscht-web
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value={{branch}}-{{date 'YYYYMMDD-HHmmss'}}