name: CI

on: [ push, pull_request ]

env:
  IMAGE_TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Importer image
      run: docker build . --file ./Horscht.Importer/Dockerfile --tag horscht-importer:${{ env.IMAGE_TAG }}

    - name: Build the Web image
      run: docker build . --file ./Horscht.Web/Dockerfile --tag horscht-web:${{ env.IMAGE_TAG }}